name = "EponymKeywordSyntax"
uuid = "d38a42db-3801-4ba0-8d69-b527598ec48c"
authors = ["Jan Weidner <jw3126@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
